services:

  postgres:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  django:
    build: .
    #    command: python python_training_2/manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: