services:

  postgres:
    image: postgres:14.0-alpine
    ports:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  django:
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: